version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db_accommodation
    env_file:
      - ./.env  
    volumes:
      - ./src:/src  
    working_dir: /src
    ports:
      - "8000:8000"  
    command: ["python", "main.py"]
