name: Pine Server Application

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-deploy:
    name: Build and Deploy Backend
    runs-on: ubuntu-22.04

    steps:
    # Etapa 1: Checkout do código
    - name: Checkout Code
      uses: actions/checkout@v3

    # Etapa 2: Configurar SSH para acesso ao servidor
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        ssh-keyscan -H 192.168.0.255 >> ~/.ssh/known_hosts

    # Etapa 3: Instalar o Docker Compose
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Etapa 4: Construir e salvar a imagem Docker usando o Docker Compose
    - name: Build and Save Docker Image
      run: |
        docker-compose -f DB_Accommodation_Avantio/docker-compose.yml build
        docker save DB_Accommodation_Avantio -o db_accommodation.tar

    # Etapa 5: Enviar o arquivo da imagem para o servidor
    - name: Transfer Docker Image to Server
      run: |
        scp -v db_accommodation.tar root@167.172.106.156:/tmp/db_accommodation.tar
    
    # Etapa 6: Fazer o deploy no servidor
    - name: Deploy Backend
      run: |
        ssh root@167.172.106.156 << 'EOF'
          docker load < /tmp/db_accommodation.tar
          docker-compose -f /path/to/docker-compose.yml up -d --no-deps avantio-app
          rm /tmp/db_accommodation.tar
        EOF

    # Etapa 7: Limpeza no ambiente local do runner
    - name: Clean Up Local Artifacts
      run: rm db_accommodation.tar

